name: EZCTL CLI CI/CD

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install .
# .github/workflows/ci-cd.yml

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ezctl
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    # retrieve your distributions here
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          repository-url: https://pypi.org/legacy/
      - run: |
          # Grab the version of the package
          version=$(cat setup.py | grep version | cut -d "'" -f 2)
          echo "Releasing for version $version"
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
